# ABOUTME: Orchestrates one end-to-end function call: builds the instruction prompt, walks the
# ABOUTME: constrained-decoding grammar (function name -> parameters), and parses the result.

"""Per-prompt orchestration: turns one natural-language request into one
resolved function call.

Brief
-----
This module is where the grammar steps defined in `grammar.py` get assembled
into an actual plan for a single prompt, driven by *data* rather than
hardcoded per-function logic: build an instruction prompt describing the
available functions, run an `EnumStep` over the declared function names, look
up that function's parameter schema, then run one value step (number/string/
boolean) per declared parameter, in declaration order. The function to call
is always the model's own choice under the enum constraint -- this module
never decides that itself via keyword matching or regex, per the subject's
"the function to call should be chosen using the LLM, not with heuristics"
rule.
"""

from __future__ import annotations

import json
from typing import Any, Union

from .errors import GenerationError, SchemaValidationError
from .grammar import EnumStep, JSONBooleanStep, JSONNumberStep, JSONStringStep, LiteralStep
from .decoder import encode_literal
from .models import FunctionCallResult, FunctionDefinition
from .vocabulary import Vocabulary


def _build_instruction_prompt(user_prompt: str, functions: list[FunctionDefinition]) -> str:
    """Render the natural-language instruction fed to the model: the task,
    the catalogue of callable functions (name/description/parameter types),
    and the user's actual request. The constrained decoder guarantees the
    *shape* of what follows is valid JSON matching the schema; this prompt is
    what gives the model a fair chance at picking the *right* function and
    argument values within that shape.

    Parameters
    ----------
    user_prompt : str
        The natural-language request to resolve (e.g. "Greet shrek").
    functions : list[FunctionDefinition]
        Every function the model is allowed to choose from.

    Returns
    -------
    str
        The full instruction text, ending right where JSON generation should
        begin.
    """
    catalogue = json.dumps(
        [
            {
                "name": fn.name,
                "description": fn.description,
                "parameters": {key: spec.type for key, spec in fn.parameters.items()},
            }
            for fn in functions
        ],
        indent=2,
    )
    return (
        "You are a function-calling assistant. Read the user's request and the list of "
        "available functions, then decide which function answers the request and with what "
        "argument values.\n\n"
        f"Available functions:\n{catalogue}\n\n"
        f'User request: "{user_prompt}"\n\n'
        "Function call:\n"
    )


def _value_step_for(type_name: str) -> Union[JSONNumberStep, JSONBooleanStep, JSONStringStep]:
    """Map a parameter's declared JSON type (from `function_definitions.json`)
    to the grammar step that generates a value of that type. Falls back to
    `JSONStringStep` for `"string"` (and as the default), since
    `models.JsonScalarType` only allows the three types checked here."""
    if type_name == "number":
        return JSONNumberStep()
    if type_name == "boolean":
        return JSONBooleanStep()
    return JSONStringStep()


def call_function_for_prompt(
    model: Any,
    vocabulary: Vocabulary,
    user_prompt: str,
    functions: list[FunctionDefinition],
) -> FunctionCallResult:
    """Run the full constrained-decoding pipeline for one natural-language prompt
    and return the resolved function call.

    The grammar walked here is built dynamically from `functions`: first an
    `EnumStep` over the declared function *names* (so the model itself picks
    which function applies, never a heuristic in this code), then -- once
    that choice is known -- one value step per parameter of *that specific*
    function, in the order it was declared. Structural JSON (braces, key
    names, commas) is emitted deterministically via `LiteralStep` and never
    left to the model to "get right".

    Parameters
    ----------
    model : Any
        An `llm_sdk.Small_LLM_Model`-compatible object (or a test double
        implementing the same `encode`/`get_logits_from_input_ids` interface).
    vocabulary : Vocabulary
        Pre-built id -> text map for `model`, from `vocabulary.Vocabulary.from_model`.
    user_prompt : str
        The natural-language request to resolve.
    functions : list[FunctionDefinition]
        Every function the model is allowed to choose from.

    Returns
    -------
    FunctionCallResult
        The original prompt (echoed through, not regenerated by the model --
        it's already known exactly, so there's no reason to make the model
        reproduce it) plus the resolved function name and arguments.

    Raises
    ------
    GenerationError
        If any grammar step can't be completed. Treated as a per-prompt
        failure by `cli.py`'s main loop, not a fatal one -- one bad prompt
        shouldn't stop the rest of the batch from being processed.
    """
    by_name = {fn.name: fn for fn in functions}
    instruction = _build_instruction_prompt(user_prompt, functions)
    input_ids = encode_literal(model, instruction)

    # 1. `{"name": "` -- structural, deterministic.
    _, input_ids = LiteralStep('{"name": "').run(model, vocabulary, input_ids)

    # 2. the function name itself: constrained to the enum of declared names.
    #    This is the one and only place the *choice* of function is made, and
    #    it's made entirely by the model's own logits under the enum mask.
    chosen_name, input_ids = EnumStep(list(by_name.keys())).run(model, vocabulary, input_ids)
    if chosen_name not in by_name:
        # Defensive only: EnumStep can only ever return one of the options it
        # was given, so this branch should be unreachable in practice.
        raise GenerationError(f"decoded function name {chosen_name!r} is not a declared function")
    function_def = by_name[chosen_name]

    # 3. `", "parameters": {` -- structural.
    _, input_ids = LiteralStep('", "parameters": {').run(model, vocabulary, input_ids)

    # 4. One value per declared parameter, in declaration order, with a
    #    structural `", "` separator between (but not after) each one.
    parameters: dict[str, object] = {}
    param_items = list(function_def.parameters.items())
    for index, (key, spec) in enumerate(param_items):
        _, input_ids = LiteralStep(f'"{key}": ').run(model, vocabulary, input_ids)
        value_text, input_ids = _value_step_for(spec.type).run(model, vocabulary, input_ids)
        parameters[key] = _coerce(value_text, spec.type)

        if index < len(param_items) - 1:
            _, input_ids = LiteralStep(", ").run(model, vocabulary, input_ids)

    _, input_ids = LiteralStep("}}").run(model, vocabulary, input_ids)

    return FunctionCallResult(prompt=user_prompt, name=chosen_name, parameters=parameters)


def _coerce(value_text: str, type_name: str) -> Any:
    """Convert a grammar step's generated text into the matching Python
    value for the output JSON: `"number"` -> `int`/`float`, `"boolean"` ->
    `bool`, everything else -> the raw string unchanged.

    Parameters
    ----------
    value_text : str
        The literal text a value step produced (e.g. ``"42"``, ``"true"``).
    type_name : str
        The parameter's declared type (`"number"`, `"string"`, or
        `"boolean"`).

    Returns
    -------
    Any
        `int` for a whole number, `float` for a fractional/exponential one,
        `bool` for a boolean, or the original `str` otherwise.

    Raises
    ------
    SchemaValidationError
        If `type_name` is `"number"` but `value_text` isn't parseable as a
        float -- this would indicate a bug in `JSONNumberStep` rather than
        anything the caller did wrong, since the grammar is supposed to
        guarantee valid number text.
    """
    if type_name == "number":
        try:
            as_float = float(value_text)
        except ValueError as exc:
            raise SchemaValidationError(f"generated number {value_text!r} could not be parsed") from exc
        # Prefer a clean int over "42.0" when the value has no fractional
        # part and wasn't written in exponential form.
        return int(as_float) if as_float.is_integer() and "e" not in value_text.lower() else as_float
    if type_name == "boolean":
        return value_text == "true"
    return value_text
